version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/shot
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
