# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ff19f3efd8717b64458bca4990535599f1a1b84ed68438de99a6751b6b7013410a6e5ab0ac746ca8da8bea4d3467262ae592e34e94159b820e49900913908e

test:
  secret_key_base: 6e61b2fe6bbd0ae5c60d69b2640c5eb5aeed5089b1d976bb632f5687020e3e571982f59a8814985a0c166f9e286f1258b4734a9621f4551657ec3b6820fe4199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
