# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

env:
  RUBY_VERSION: 2.7.2
  NODE_VERSION: 15.13.0
  RAILS_ENV: test
  POSTGRES_USER: postgres
  POSTGRES_DB: shotn_test
  POSTGRES_PASSWORD: postgres

name: Ruby

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      # uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: '2.7.2'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Create database
      run: bundle exec rails db:test:prepare
    - name: Run tests
      run: bundle exec rspec spec
